[project]
version = "0.0.1"
name = "finitum"
license = { text = "MIT" }
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.16.5",
    "bs4>=0.0.2",
    "celery>=5.5.3",
    "cryptography>=48.0.1",
    "dash>=3.2.0",
    "fastapi[standard]>=0.117.1",
    "google-api-python-client>=2.182.0",
    "google-api-python-client-stubs>=1.30.0",
    "google-auth-oauthlib>=1.2.2",
    "granian[reload]>=2.5.3",
    "itsdangerous>=2.2.0",
    "pandas>=2.3.2",
    "psycopg2-binary>=2.9.10",
    "pwdlib[argon2]>=0.2.1",
    "pydantic[email]>=2.11.7",
    "pyjwt>=2.10.1",
    "pyright>=1.1.405",
    "pytest>=8.4.2",
    "pytest-parametrize>=1.5.0",
    "pytz>=2025.2",
    "redis>=6.4.0",
    "requests>=2.32.5",
    "ruff>=0.13.2",
    "slowapi>=0.1.9",
    "sqlalchemy>=2.0.43",
    "sqlmodel>=0.0.24",
    "starlette>=0.48.0",
    "ty>=0.0.1a21",
]

[project.scripts]
app = "src.api.server:app"

[tool.ruff]
target-version = "py313"
fix = true

# Formatting
line-length = 120
indent-width = 4

exclude = [
    ".git",
    ".ruff_cache",
    "__pycache__",
    ".venv",
    "ui",
]

[tool.ruff.lint]
preview = true
select = [
    "E", # Errors
    "W", # Warnings
    "F",  # Pyflakes rules
    "B", # flake-8 bugbear rules
    "PL", # Pylint rules
    "DJ", # Django rules
    "EM", # Error handling
    "ICN", # Import conventions
    "LOG", # Logging rules
    "G",  # Logging format
    "PT", # PyTest style
    "RET", # Return statements
    "SIM", # Simplicity
    "ARG", # Unused arguments
    "C4", # Comprehensions
    "TC", # Type checker rules
    "C90", # Cyclomatic complexity
    "N",  # Naming conventions PEP8
    "UP", # Code modernization suggestions
    "TRY", # Try/Except rules
    "RUF", # Ruff specific rules
    "ANN", # Type annotations
    "ASYNC", # Asynchronous code rules
    "S", # Security issues
]

# Ignored rules
ignore = [
    # ERRORS AND PEP8
    "E501",  # Line too long
    "E272",  # Multiple spaces before keyword, dict formatting has a warning with this
    "B008",  # FastAPI deps injection

    # ANNOTATIONS
    "ANN204", # Missing type annotation for especial method return
    "ANN002", # Missing type annotation for function *args
    "ANN003", # Missing type annotation for function **kwargs
    "ANN401", # Use Any

    # LOGGING
    "G201", # Use error instead of exception

    #TODOs
    "TD003", # Missing link in TODO comment

    # SIMPLICITY
    "SIM108", # Ternary operator should be used
    "SIM910", # Use dict.get() without default value

    # RETURN STATEMENTS
    "RET504", # Innecesary assignment before return

    # RUFF SPECIFIC RULES
    "RUF012", # Mutable class attributes should be annotated with typing.ClassVar

    # TRY/EXCEPT
    "TRY003", # Avoid specifying long messages outside the exception class
    "TRY301", # Abstract raise to an inner function
    "TRY400", # Prefer loggin.exception over logging.error

    # ERROR MESSAGES
    "EM101", # Comments in except block

    "RUF003", # single quote usage in comments
    "PLC0415", # Ignore in top-level

    # TESTS
    "S101",    # assert statements in tests - they're a standard part of testing

    # WHITESPACES
    "W293", # Blank line contains whitespace

    # REFACTOR
    "PLR0904", # Too many public methods > 20
    "PLR0913", # Too many arguments in function definition (6 > 5)
    "PLR0917", # Too many positional arguments (6/ 5)
    "PLR6301", # Allow the use of non-static methods in Django views (self is required)
]

# Per-file ignores
[tool.ruff.lint.per-file-ignores]
"**/tests/*" = [
    "SLF001",  # accessing private members in tests - sometimes needed to verify internal state
    "T201",    # print statements in tests - useful for debugging test failures
    "S404",    # subprocess calls in tests - may be needed for testing system interactions
    "S603",    # subprocess calls without shell=False in tests
    "S607",    # use of subprocess.run with partial path in tests
    "S106",    # hardcoded passwords in tests - needed for test fixtures
    "PT027",   # pytest raises without match - not all exceptions need message validation
    "PLC2701", # import private members
    "ANN201",  # The return type is not necessary in tests; it is always None
    "PLR2004", # Magic numbers
    "ANN001",  # Argument type
    "S105",    # Hardcoded password
]

# McCabe complexity
[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.format]
indent-style = "space"
quote-style = "double"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
pythonpath = ["src"]
python_files = ["test_*.py", "*_tests.py"]

[tool.alembic]

# path to migration scripts.
# this is typically a path given in POSIX (e.g. forward slashes)
# format, relative to the token %(here)s which refers to the location of this
# ini file
script_location = "%(here)s/alembic"

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# Uncomment the line below if you want the files to be prepended with date and time
# see https://alembic.sqlalchemy.org/en/latest/tutorial.html#editing-the-ini-file
# for all available tokens
# file_template = "%%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d%%(minute).2d-%%(rev)s_%%(slug)s"

# additional paths to be prepended to sys.path. defaults to the current working directory.
prepend_sys_path = [
    "."
]

# timezone to use when rendering the date within the migration file
# as well as the filename.
# If specified, requires the python>=3.9 or backports.zoneinfo library and tzdata library.
# Any required deps can installed by adding `alembic[tz]` to the pip requirements
# string value is passed to ZoneInfo()
# leave blank for localtime
# timezone =

# max length of characters to apply to the "slug" field
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a source .py file to be detected as revisions in the
# versions/ directory
# sourceless = false

# version location specification; This defaults
# to <script_location>/versions.  When using multiple version
# directories, initial revisions must be specified with --version-path.
# version_locations = [
#    "%(here)s/alembic/versions",
#    "%(here)s/foo/bar"
# ]


# set to 'true' to search source files recursively
# in each "version_locations" directory
# new in Alembic version 1.10
# recursive_version_locations = false

# the output encoding used when revision files
# are written from script.py.mako
# output_encoding = "utf-8"

# This section defines scripts or Python functions that are run
# on newly generated revision scripts.  See the documentation for further
# detail and examples
# [[tool.alembic.post_write_hooks]]
# format using "black" - use the console_scripts runner,
# against the "black" entrypoint
# name = "black"
# type = "console_scripts"
# entrypoint = "black"
# options = "-l 79 REVISION_SCRIPT_FILENAME"
#
# [[tool.alembic.post_write_hooks]]
# lint with attempts to fix using "ruff" - use the module runner, against the "ruff" module
# name = "ruff"
# type = "module"
# module = "ruff"
# options = "check --fix REVISION_SCRIPT_FILENAME"
#
# [[tool.alembic.post_write_hooks]]
# Alternatively, use the exec runner to execute a binary found on your PATH
# name = "ruff"
# type = "exec"
# executable = "ruff"
# options = "check --fix REVISION_SCRIPT_FILENAME"

[tool.ty.environment]
root = ["./src", "."]

[tool.ty.src]
include = [
    "src",
    "tests",
]
