[project]
version = "0.0.1"
name = "fin-make"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "dash>=3.2.0",
    "dotenv>=0.9.9",
    "granian>=2.5.3",
    "pandas>=2.3.2",
    "psycopg2>=2.9.10",
    "pytest>=8.4.2",
    "pytz>=2025.2",
    "sqlmodel>=0.0.24",
]

[tool.ruff]
target-version = "py312"

# Formatting
line-length = 120
indent-width = 4

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
pythonpath = "src"
python_files = ["test_*.py", "*_tests.py"]

