"""add is_valid to google_credentials

Revision ID: 209481f76956
Revises: add_bank_to_users
Create Date: 2026-02-03 23:01:24.354682

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "209481f76956"
down_revision: str | Sequence[str] | None = "add_bank_to_users"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_google_credentials", sa.Column("is_valid", sa.Boolean(), default=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_google_credentials", "is_valid")
    # ### end Alembic commands ###
