"""initial

Revision ID: 8a8880bc72e6
Revises:
Create Date: 2025-09-24 02:04:52.998429

"""

import sqlmodel
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8a8880bc72e6"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

categories = (
    "GENERAL",
    "FOOD",
    "EDUCATION",
    "TRANSPORT",
    "SERVICES",
    "TRANSFERS",
    "CLOTHING",
    "ENTERTAINMENT",
    "SPORTS",
    "LOAN",
    "ATM_WITHDRAWAL",
    "INVESTMENTS",
    "HOUSING",
    "EXTERNAL_FOOD",
    "RECREATION",
    "ONLINE",
    "COMMISSIONS",
    "TRAVEL",
    "HEALTH",
    "FAMILY",
    "LAUNDRY",
    "BOOKS",
    "PURIFIED_WATER",
)

cat_enum = sa.Enum(
    *categories,
    name="expensecategory",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_update", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "expenses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("commerce", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("currency", sa.Enum("USD", "CLP", name="currency"), nullable=False),
        sa.Column(
            "category",
            cat_enum,
            nullable=False,
        ),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
    )
    op.create_index(op.f("ix_expenses_commerce"), "expenses", ["commerce"], unique=False)
    op.create_table(
        "transferences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("recipient", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("currency", sa.Enum("USD", "CLP", name="currency"), nullable=False),
        sa.Column(
            "category",
            cat_enum,
            nullable=False,
        ),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
    )
    op.create_index(op.f("ix_transferences_recipient"), "transferences", ["recipient"], unique=False)
    op.create_table(
        "user_google_credentials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("refresh_token", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("granted_scopes", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_google_credentials")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_transferences_recipient"), table_name="transferences")
    op.drop_table("transferences")
    op.drop_index(op.f("ix_expenses_commerce"), table_name="expenses")
    op.drop_table("expenses")
    # ### end Alembic commands ###
