"""initial

Revision ID: 8a8880bc72e6
Revises:
Create Date: 2025-09-24 02:04:52.998429

"""

import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8a8880bc72e6"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "expense",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("commerce", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("currency", sa.Enum("USD", "CLP", name="currency"), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "GENERAL",
                "FOOD",
                "EDUCATION",
                "TRANSPORT",
                "SERVICES",
                "TRANSFERS",
                "CLOTHING",
                "ENTERTAINMENT",
                "SPORTS",
                "LOAN",
                "ATM_WITHDRAWAL",
                "INVESTMENTS",
                "HOUSING",
                "EXTERNAL_FOOD",
                "RECREATION",
                "ONLINE",
                "COMMISSIONS",
                "TRAVEL",
                "HEALTH",
                "FAMILY",
                "LAUNDRY",
                "BOOKS",
                "PURIFIED_WATER",
                name="expensecategory",
            ),
            nullable=False,
        ),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_expense_commerce"), "expense", ["commerce"], unique=False)
    op.create_table(
        "transference",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recipient", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("currency", sa.Enum("USD", "CLP", name="currency"), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "GENERAL",
                "FOOD",
                "EDUCATION",
                "TRANSPORT",
                "SERVICES",
                "TRANSFERS",
                "CLOTHING",
                "ENTERTAINMENT",
                "SPORTS",
                "LOAN",
                "ATM_WITHDRAWAL",
                "INVESTMENTS",
                "HOUSING",
                "EXTERNAL_FOOD",
                "RECREATION",
                "ONLINE",
                "COMMISSIONS",
                "TRAVEL",
                "HEALTH",
                "FAMILY",
                "LAUNDRY",
                "BOOKS",
                "PURIFIED_WATER",
                name="expensecategory",
            ),
            nullable=False,
        ),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_transference_recipient"), "transference", ["recipient"], unique=False)
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_update", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    op.create_table(
        "usergooglecredentials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("refresh_token", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("granted_scopes", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("usergooglecredentials")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_transference_recipient"), table_name="transference")
    op.drop_table("transference")
    op.drop_index(op.f("ix_expense_commerce"), table_name="expense")
    op.drop_table("expense")
    # ### end Alembic commands ###
