"""empty message

Revision ID: 954559348e2e
Revises: 8a8880bc72e6
Create Date: 2025-10-05 02:13:01.805376

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "954559348e2e"
down_revision: str | Sequence[str] | None = "8a8880bc72e6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_google_credentials", sa.Column("token_uri", sa.Text(), nullable=True))
    op.add_column("user_google_credentials", sa.Column("client_id", sa.Text(), nullable=True))
    op.add_column("user_google_credentials", sa.Column("client_secret", sa.Text(), nullable=True))
    op.add_column("user_google_credentials", sa.Column("scopes_json", sa.Text(), nullable=True))
    op.add_column("user_google_credentials", sa.Column("granted_scopes_json", sa.Text(), nullable=True))
    op.add_column("user_google_credentials", sa.Column("expiry", sa.DateTime(), nullable=True))
    op.add_column("user_google_credentials", sa.Column("id_token", sa.Text(), nullable=True))
    op.alter_column(
        "user_google_credentials", "token", existing_type=sa.VARCHAR(length=255), type_=sa.Text(), nullable=True
    )
    op.alter_column(
        "user_google_credentials", "refresh_token", existing_type=sa.VARCHAR(length=255), type_=sa.Text(), nullable=True
    )
    op.drop_column("user_google_credentials", "granted_scopes")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_google_credentials", sa.Column("granted_scopes", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.alter_column(
        "user_google_credentials",
        "refresh_token",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=255),
        nullable=False,
    )
    op.alter_column(
        "user_google_credentials", "token", existing_type=sa.Text(), type_=sa.VARCHAR(length=255), nullable=False
    )
    op.drop_column("user_google_credentials", "id_token")
    op.drop_column("user_google_credentials", "expiry")
    op.drop_column("user_google_credentials", "granted_scopes_json")
    op.drop_column("user_google_credentials", "scopes_json")
    op.drop_column("user_google_credentials", "client_secret")
    op.drop_column("user_google_credentials", "client_id")
    op.drop_column("user_google_credentials", "token_uri")
    # ### end Alembic commands ###
